apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: hbc08/bch:e3d2fb76932e91b4dcadd24278ace56e7a08eb44
        ports:
        - containerPort: 8881
        env:
        # - name: USER_NAME
        #   valueFrom:
        #     secretKeyRef:
        #       name: my-mongo-secret-name
        #       key: mongo-user
        # - name: USER_PWD
        #   valueFrom:
        #     secretKeyRef:
        #       name: my-mongo-secret-name
        #       key: mongo-password 
        # - name: MONGODB_URL
        #   valueFrom:
        #     configMapKeyRef:
        #       name: mongo-config-name
        #       key: mongo-url
          - name: MONGODB_URL
            value: mongodb://mongouser:mongopassword@my-mongo-service-name:27017
---
apiVersion: v1
kind: Service
metadata:
  name: my-webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8881
      targetPort: 8881
      nodePort: 30201